import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './styles.css'
import './training.css'
import './editor-v2.css'
import './editor-v3.css'
import './workshop.css'
import './editor-v4.css'
import './editor-v5.css'
import './editor-v6.css'
import './editor-v7.css'
import './editor-v8.css'
import './tube-opacity.css'
import './project.css'
import './feedback.css'
import './landing.css'
import './tour.css'
import './tour.css'
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
